{{- if and .Values.global.rbac.create .Values.global.rbac.userRoles.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "helm-locker.name" . }}-admin
  labels: {{ include "helm-locker.labels" . | nindent 4 }}
  {{- if .Values.global.rbac.userRoles.aggregateToDefaultRoles }}
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
  {{- end }}
rules:
- apiGroups:
  - helm.cattle.io
  resources:
  - helmreleases
  - helmreleases/finalizers
  - helmreleases/status
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "helm-locker.name" . }}-edit
  labels: {{ include "helm-locker.labels" . | nindent 4 }}
  {{- if .Values.global.rbac.userRoles.aggregateToDefaultRoles }}
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
  {{- end }}
rules:
- apiGroups:
  - helm.cattle.io
  resources:
  - helmreleases
  - helmreleases/status
  verbs:
  # Since Helm Locker executes with cluster-admin privileges, only an admin gets mutating permissions for them
  - 'get'
  - 'list'
  - 'watch'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "helm-locker.name" . }}-view
  labels: {{ include "helm-locker.labels" . | nindent 4 }}
  {{- if .Values.global.rbac.userRoles.aggregateToDefaultRoles }}
    rbac.authorization.k8s.io/aggregate-to-view: "true"
  {{- end }}
rules:
- apiGroups:
  - helm.cattle.io
  resources:
  - helmreleases
  - helmreleases/status
  verbs:
  - 'get'
  - 'list'
  - 'watch'
{{- end }}
