apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "helm-locker.name" . }}
  labels: {{ include "helm-locker.labels" . | nindent 4 }}
    app: {{ template "helm-locker.name" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  # By default, Helm Locker does not know what it will need permissions to be able to lock, so it is granted a cluster-admin role by default
  name: "cluster-admin"
subjects:
- kind: ServiceAccount
  name: {{ template "helm-locker.name" . }}
  namespace: {{ template "helm-locker.namespace" . }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "helm-locker.name" . }}
  namespace: {{ template "helm-locker.namespace" . }}
  labels: {{ include "helm-locker.labels" . | nindent 4 }}
    app: {{ template "helm-locker.name" . }}
{{- if .Values.global.imagePullSecrets }}
imagePullSecrets: {{ toYaml .Values.global.imagePullSecrets | nindent 2 }}
{{- end }}

