apiVersion: v1
kind: ConfigMap
metadata:
  name: my-config-map
  namespace: {{ .Release.Namespace }}
data:
  config: |- 
{{ .Values.data | toYaml | indent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-config-map-2
  namespace: {{ .Release.Namespace }}
data:
  config: |- 
{{ .Values.data | toYaml | indent 4 }}